### ISSUE TITLE
Storing number types

### ISSUE THREAD

**Issue by pflannery** [Polymer/NodeBind#18]
I'm finding that when I use the input type=number element I get strings instead of numbers.

I want to propose a change to [at part of the code](https://github.com/Polymer/NodeBind/blob/master/src/NodeBind.js#L175-L180)

to include this:

```js
if (input.type==='number')
  observable.setValue(input.valueAsNumber);
else
  observable.setValue(input[property]);
```

This then stores the user input as a number type

**Comment by jmesserly** [comment]
Yeah, good point. It already has special handling for other types (e.g. treat radio and checkbox as boolean values), and it will get serialized from number -> string going in the other direction already.
